export const metadata = {
  title: "Registration",
  description: "Generated by create next app",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex items-center justify-center min-h-screen bg-orange-200">
          <div className="bg-white p-8 rounded-xl shadow-lg w-96">
            {children}
          </div>
        </div>
    </body>
    </html>
  );
}